spring:
  application:
    name: Inventory-Management
  h2:
    console:
      enabled: true
  datasource:
    platform: h2
    url: jdbc:h2:~/inventorymgmt;AUTO_SERVER=TRUE
  thymeleaf:
    cache: false
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 9910

management:
  endpoint:
    health:
      enabled: true
      show-details: always

