eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

spring:
  application:
    name: InventoryManagement
server:
  port: 9910
  
management:
  endpoint:
    health:
      enabled: true
      show-details: always