eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

spring:
  application:
    name: Inventory-Management
  h2:
    console:
      enabled: true
  datasource:
    platform: h2
    url: jdbc:h2:~/inventorymgmt;AUTO_SERVER=TRUE
    
server:
  port: 9910
  
management:
  endpoint:
    health:
      enabled: true
      show-details: always