spring:
  cloud:
    config:
      server:
#        git:
#          uri: C:\Users\uts58\IdeaProjects\utshaTraders\config
#          clone-on-start: true
        native:
          search-locations: file:///C:/Users/uts58/IdeaProjects/utshaTraders/config
  application:
    name: config-server
  profiles:
    active: native

server:
  port: 8888

management:
  endpoint:
    health:
      enabled: true
      show-details: always

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}